name: main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Run linting and tests
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
        env:
          CI: true
